---
- name: create application directory
  file:
    dest: "{{ cat_install_dir }}"
    state: directory

- name: install shell script
  template:
    src: cattail.sh
    dest: "{{ cat_install_dir }}/cattail.sh"
    mode: "a+x"
...