---
- name: create application directory
  file:
    dest: "{{ cat_install_dir }}"
    state: directory

- name: install shell script
  template:
    src: cattail.sh
    dest: "{{ cat_install_dir }}/cattail.sh"
    mode: "a+x"

- name: install service
  become: yes
  template:
    src: cattail.conf
    dest: "/etc/supervisor/conf.d/cattail.conf"
  notify:
    - reload supervisor config
    - restart cattail service
...